version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  install_and_lint:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: '18.19.0'
      - run: node --version
      - run: sudo npm i 
      - run: sudo npm run lint
  deploy:
    executor: node/default
    steps:
      - checkout
      - run: npx semantic-release

workflows:
  test_deploy:
    jobs:
      - install_and_lint
      - node/test:
          requires:
            - install_and_lint
      - deploy:
          context: org_global
          filters:
            branches:
              only: main
          requires:
            - install_and_lint
            - node/test